In [2]:
import numpy as np

###  1) Write a NumPy program to test whether none of the elementsof a given array is zero

In [51]:
a=np.array([[1,2],[3,0]])
flag=False
for i in range(len(a)):
    for j in range(len(a[i])):
        if a[i][j]==0:
            flag=False
        else:
            flag=True
print(flag)

False


### 2) Write a NumPy program to test whether any of the elements of a given array is non-zero.

In [59]:
b=np.array([[0,6,3],[0,0,8]])
flag=False
for i in range(len(b)):
    for j in range(len(b[i])):
        if b[i][j]!=0:
            flag=True
        else:
            flag=False
print(flag)
   

True


#### 3)Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given

In [69]:
a=np.array([1,3,4,6,8,9])
b=np.array([1,3,4,6,8,9])
lst=[]
for i,j in zip(a,b):
    if i==j:
        lst.append(True)
    else:
        lst.append(False)
print(lst)           
            

[True, True, True, True, True, True]


### 4)Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

In [64]:
a=np.zeros(10)
print("array of 10 zeros",a)

b=np.ones(10)
print("array of 10 ones",b)

c=np.ones(10)*5
print("array of 10 fives",c)

array of 10 zeros [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
array of 10 ones [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
array of 10 fives [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


### 5) Write a NumPy program to create an array of the integers from 30 to70.

In [66]:
a=np.arange(30,71)
a

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

### 6) Write a NumPy program to create a 3x3 identity matrix 

In [68]:
a=np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 7) Write a NumPy program to generate a random number between 0 and 1 

In [70]:
np.random.normal(0,1)

0.7648441963524062

##### 8) Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution 

In [74]:
np.random.normal(0,1,15)

array([ 0.72869842,  1.00602026, -0.5779947 , -0.11507832,  0.26080399,
       -0.05507085, -1.8321438 ,  0.09214924,  0.26505372, -0.37039704,
       -0.08674423,  0.9547358 , -0.60796606, -1.3128006 ,  0.54140145])

##### 9) Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last

In [89]:
np.arange(16,55)

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54])

#### 10)Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10

In [90]:
np.random.randint(0, 11, 5)

array([1, 2, 8, 4, 8])

##### 11) Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.


In [2]:
from numpy import matlib

In [104]:
a=matlib.ones((10,10))
a

matrix([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [105]:
a[1:9,1:9]=0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 12) Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4,5

In [124]:
a=matlib.zeros((5,5))
a

matrix([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [136]:
a=matlib.diag([1,2,3,4,5])
a

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

##### 13) Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.

In [18]:
a=np.random.randint(0, 2, (4,4))
a

array([[0, 1, 0, 1],
       [1, 1, 1, 0],
       [0, 1, 1, 1],
       [1, 0, 0, 0]])

In [19]:
for i in range(len(a)):
    for j in range(len(a[i])):
        if i==j:
            a[i][j]=0
print(a)

array([[0, 1, 0, 1],
       [1, 0, 1, 0],
       [0, 1, 0, 1],
       [1, 0, 0, 0]])

##### 14)Write a NumPy program to save two given arrays into a single file in compressed format (.npz format) and load it.


In [10]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
np.savez('arrays.npz', a, b)
with np.load('array.npz') as data:
    a2 = data['a']
    b2 = data['b']
    print(a2)
    print(b2)

[0 1 2 3 4]
[10 11 12 13 14 15]


##### 15) Write a NumPy program to create a one dimensional array of forty pseudo-randomly generated values.

In [20]:
np.random.randint(1,30,40)

array([ 4, 17, 11, 28, 29, 18, 15, 12, 27, 10, 17, 17,  5, 17, 19,  2, 21,
       13,  3, 28, 25,  4, 10,  6, 11, 20, 20, 14, 14,  8, 19,  9, 10,  5,
       26, 26,  6,  6, 24,  8])

##### 16) Write a NumPy program to extract all numbers from a given array which are less and greater than a specified number

In [170]:
a=np.array([[1,2,4],[40,7,32],[9,6,8]])
lst1=[]
for i in range(len(a)):
    for j in range(len(a[i])):
        if a[i][j]<10:
            lst1.append(a[i][j])
print(lst1)        

[1, 2, 4, 7, 9, 6, 8]
